# docker-compose.prod.yml
version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    # The image name is parameterized using an environment variable.
    # In production, this value will be supplied via your CI/CD pipeline.
    image: ${IMAGE_NAME}
    ports:
      - "80:8501"  # Maps production port 80 to container port 8501
    environment:
      - ENV=production
      - OTHER_PROD_VAR=value
    restart: always
